Docs/urls.py
from django.conf.urls import patterns, include, url
from api import urls
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/',include(urls, namespace='api')),
)

api/urls.py
from api.views import ContactView,  AuthorListView, AuthorDetail, test

__author__ = 'daniel'

from django.conf.urls import patterns, include, url, handler404


urlpatterns = [
    url(r'^test/$', test, name='test'),
    url(r'^success/$', ContactView.as_view(), name='success'),
    url(r'^author-details/(?P<pk>[0-9]+)$', AuthorDetail.as_view(), name='author-details'),
    url(r'^author-list/(?P<pk>[0-9]+)$', AuthorListView.as_view(), name='author-list'),
]

api/models.py
# models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)

    class Meta:
        ordering = ["-name"]

    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    foo = models.CharField(max_length=100, null=True)
    publisher = models.ForeignKey(Publisher)



    class Meta:
        ordering = ['salutation']


    def __str__(self):              # __unicode__ on Python 2
        return self.name


class BookManager(models.Manager):
    def foo(self):
        return super(BookManager, self).get_queryset().filter(title='nowa')

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher)

    objects = BookManager()

    def save(self,*args,**kwargs):
        super(Book,self).save(*args, **kwargs)
        print(self.pk)

api/views.py
from django.views.generic import ListView, DetailView
from django.core.urlresolvers import reverse
from django import forms
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView

from .models import Author
sss

sdasds
class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    date = forms.DateField(required=False)


    def send_email(self):
        # send email using the self.cleaned_data dictionar y
        pass


    def is_valid(self):
        return super(ContactForm, self).is_valid()

class ContactView(TemplateView):
    template_name = 'authors.html'

    def get_context_data(self, **kwargs):
        ctx = super(ContactView, self).get_context_data(**kwargs)
        # do sth with ctx
        return ctx


class AuthorListView(ListView):
    template_name = 'authors.html'
    model = Author

    def get_context_data(self, **kwargs):
        ctx = super(AuthorListView, self).get_context_data(**kwargs)
        ctx.update({'pk': self.kwargs['pk']})
        return ctx


class AuthorReviewView(SingleObjectMixin, FormView):
    template_name = 'author_details.html'
    form_class = ContactForm
    model = Author

    def get_success_url(self):
        self.object = self.get_object()
        return reverse('api:author-details', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        #self.object = self.get_object()
        ctx = super(AuthorReviewView, self).get_context_data(**kwargs)
        return ctx


class AuthorDetailView(DetailView):
    template_name = 'author_details.html'
    model = Author

    def get_context_data(self, **kwargs):
        ctx = super(AuthorDetailView, self).get_context_data(**kwargs)
        ctx['form'] = ContactForm()
        return ctx


class AuthorDetail(View):

    def get(self, request, *args, **kwargs):
        view = AuthorDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = AuthorReviewView.as_view()
        return view(request, *args, **kwargs)

from django.shortcuts import render_to_response
from django.template import RequestContext
from tasks import create_author



from django.http import HttpResponse

def test(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        print(form)
        if form.is_valid():
            return HttpResponse("wszystko ok")
    else:
        form = ContactForm({'name':'daniel'})
        print(form)
    return render_to_response('detailed.html',context={'form':form},context_instance=RequestContext(request))

from django.forms import ModelForm


class A(ModelForm):
    def clean(self):
        return super(A, self).is_valid()

templates/author_details.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{% load tag_extras %}

<h1> {{ author.name|cut_own:'4' }}</h1>


{% for book in book_list %}
    <p> {{ book.title }} </p>
{% endfor %}

<a href="{% url 'api:author-details' 2 %}">link</a>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>



</body>
</html>

templates/authors.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<h2> {{ pk }}</h2>

{% for author in author_list %}
    <p> {{ author.name }} </p>
{% endfor %}

</body>
</html>

templates/detailed.html
{% extends 'outline.html' %}

{% block sth_else %}

<form action="." method="post">
    {% csrf_token %}
{{ form }}
    <input type="submit" value="Przeslij">
</form>

{% endblock %}

templates/inner.html
<form method="post">
   {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>

templates/outline.html
{% extends 'parent_outline.html' %}

{% block details %}
    <p> Blok details rodzica</p>
{% endblock %}

{% block sth_else %}


{% endblock %}

templates/test.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{{ request.user }}

</body>
</html>